# Generated by Django 2.1 on 2018-08-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postovi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user_name',
            new_name='user',
        ),
    ]
