# Generated by Django 2.1 on 2018-08-19 22:44

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('postovi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
