# Generated by Django 2.1 on 2018-08-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postovi', '0003_auto_20180826_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
